matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
      - .github/wordlist.txt # <-- put path to custom dictionary file here
    encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
        - pymdownx.superfences:
    - pyspelling.filters.html:
        comments: true
        attributes:
          - title
          - alt
        ignores:
          - 'code'
          - 'pre'
  sources:
    - '!**/node_modules/**/*|!**/CHANGELOG.md|**/*.md'
  default_encoding: utf-8
