// @generated by protobuf-ts 2.8.0
// @generated from protobuf file "message.proto" (package "webrtc.pb", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message webrtc.pb.Message
 */
export interface Message {
    /**
     * @generated from protobuf field: optional webrtc.pb.Message.Flag flag = 1;
     */
    flag?: Message_Flag;
    /**
     * @generated from protobuf field: optional bytes message = 2;
     */
    message?: Uint8Array;
}
/**
 * @generated from protobuf enum webrtc.pb.Message.Flag
 */
export enum Message_Flag {
    /**
     * The sender will no longer send messages.
     *
     * @generated from protobuf enum value: CLOSE_WRITE = 0;
     */
    CLOSE_WRITE = 0,
    /**
     * The sender will no longer read messages.
     *
     * @generated from protobuf enum value: CLOSE_READ = 1;
     */
    CLOSE_READ = 1,
    /**
     * The local endpoint abruptly terminates the stream. The remote endpoint
     * may discard any in-flight data.
     *
     * @generated from protobuf enum value: RESET = 2;
     */
    RESET = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class Message$Type extends MessageType<Message> {
    constructor() {
        super("webrtc.pb.Message", [
            { no: 1, name: "flag", kind: "enum", opt: true, T: () => ["webrtc.pb.Message.Flag", Message_Flag] },
            { no: 2, name: "message", kind: "scalar", opt: true, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<Message>): Message {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Message>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Message): Message {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional webrtc.pb.Message.Flag flag */ 1:
                    message.flag = reader.int32();
                    break;
                case /* optional bytes message */ 2:
                    message.message = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Message, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional webrtc.pb.Message.Flag flag = 1; */
        if (message.flag !== undefined)
            writer.tag(1, WireType.Varint).int32(message.flag);
        /* optional bytes message = 2; */
        if (message.message !== undefined)
            writer.tag(2, WireType.LengthDelimited).bytes(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message webrtc.pb.Message
 */
export const Message = new Message$Type();
