// Warning: This file is automatically synced from https://github.com/ipfs/ci-sync so if you want to change it, please change it there and ask someone to sync all repositories.
javascript([
    'node_modules': [
        'ipfs-api': 'github:ipfs/js-ipfs-api#test/easier-mocking'
    ]
])
