export const DEFAULT_INITIAL_GATEWAY_SEARCH_INTERVAL = 5_000
export const DEFAULT_INITIAL_GATEWAY_SEARCH_TIMEOUT = 5_000
export const DEFAULT_INITIAL_GATEWAY_SEARCH_MESSAGE_INTERVAL = 1_000

export const DEFAULT_GATEWAY_SEARCH_TIMEOUT = 60_000
export const DEFAULT_GATEWAY_SEARCH_INTERVAL = 300_000
export const DEFAULT_GATEWAY_SEARCH_MESSAGE_INTERVAL = 10_000
